# Topic 4: Spring Security Architecture Demo Configuration
spring.application.name=banking-security-demo
server.port=8084

# H2 File-Based Local Database Setup (Stored in project ./data folder)
spring.datasource.url=jdbc:h2:file:./data/bankingsecdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.headers.frame-options=sameorigin

# Security Debug Logging
logging.level.org.springframework.security=DEBUG
