package com.example.customer.model; // Declares model package for database entity classes

import jakarta.persistence.Column; // JPA annotation for database column mapping
import jakarta.persistence.Entity; // JPA annotation marking class as database entity
import jakarta.persistence.GeneratedValue; // JPA annotation for primary key value generation strategy
import jakarta.persistence.GenerationType; // Enum specifying database identity strategy
import jakarta.persistence.Id; // JPA annotation marking primary key field
import jakarta.persistence.Table; // JPA annotation specifying target database table name

/**
 * Customer JPA Entity class representing 'customers' table in database.
 * Rule Enforced: 'name' is non-updatable in database schema (updatable = false).
 */
@Entity // Tells Hibernate/JPA to map this class to a database table
@Table(name = "customers") // Specifies database table name as 'customers'
public class Customer {

    @Id // Marks customerId field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Uses database auto-increment identity column
    @Column(name = "customer_id") // Maps field to database column name 'customer_id'
    private Long customerId; // Unique identifier for each customer

    @Column(name = "name", nullable = false, updatable = false) // Name cannot be null AND cannot be updated after creation
    private String name; // Full name of customer (READ-ONLY after creation)

    @Column(name = "email", nullable = false) // Maps to 'email' column, cannot be null
    private String email; // Customer email address (EDITABLE)

    @Column(name = "location", nullable = false) // Maps to 'location' column, cannot be null
    private String location; // Customer city/location (EDITABLE)

    /**
     * Default no-argument constructor required by JPA specification.
     */
    public Customer() {
    }

    /**
     * All-argument constructor for creating instance with existing ID.
     */
    public Customer(Long customerId, String name, String email, String location) {
        this.customerId = customerId; // Assign customer ID
        this.name = name; // Assign customer name
        this.email = email; // Assign customer email
        this.location = location; // Assign customer location
    }

    /**
     * Constructor for creating new customer without ID (ID auto-generated by DB).
     */
    public Customer(String name, String email, String location) {
        this.name = name; // Assign customer name
        this.email = email; // Assign customer email
        this.location = location; // Assign customer location
    }

    // Getter for customerId
    public Long getCustomerId() {
        return customerId;
    }

    // Setter for customerId
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    // Getter for name
    public String getName() {
        return name;
    }

    // Setter for name
    public void setName(String name) {
        this.name = name;
    }

    // Getter for email
    public String getEmail() {
        return email;
    }

    // Setter for email
    public void setEmail(String email) {
        this.email = email;
    }

    // Getter for location
    public String getLocation() {
        return location;
    }

    // Setter for location
    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerId=" + customerId +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", location='" + location + '\'' +
                '}';
    }
}
