# Topic 5: Spring Security Stateless JWT Demo Configuration
spring.application.name=banking-jwt-security-demo
server.port=8085

# H2 File-Based Database Setup
spring.datasource.url=jdbc:h2:file:./data/bankingjwtdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.headers.frame-options=sameorigin

# JWT Security Configuration Properties
# Secret Key (256-bit base64 / HMAC-SHA256 secret)
app.jwt.secret=StandardCharteredSecretKeyForJWTAuthentication2026SuperSecureKeyWith256BitsLength!
# Expiration Time in Milliseconds (24 Hours = 86,400,000 ms)
app.jwt.expiration-ms=86400000
