# Server Port
server.port=8080

# Application Name
spring.application.name=spring-security-inmemory-demo

# Swagger OpenAPI Path Settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
