# Topic 3: Spring Data JPA Demo Configuration
spring.application.name=banking-jpa-demo
server.port=8083

# H2 File-Based Local Database Setup (Stored in project ./data folder)
spring.datasource.url=jdbc:h2:file:./data/bankingjpadb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Syntax Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
